name: lifestream
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.0-116.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flat_list: ^0.1.14
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
  - lib/recursos/json/hospitais.json
  - lib/recursos/imagens/produto.jpeg
  - lib/recursos/imagens/avatar.png
  - lib/recursos/imagens/logo.png
  - lib/recursos/imagens/UPA.png
  - lib/recursos/imagens/HGVC.png
  - lib/recursos/imagens/HSV.png
  - lib/recursos/imagens/HMEM.png
